apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: incident-api
  namespace: monitoring
  labels:
    release: incident-monitoring
spec:
  selector:
    matchLabels:
      monitoring: incident
  namespaceSelector:
    matchNames:
      - incident-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
